BINARY=zhttpd
LDFLAGS=-lboost_thread -L/usr/local/lib
CFLAGS=-O2 -I/usr/local/include
CXXFLAGS=$(CFLAGS)

all: $(BINARY)

zhttpd: main.o server.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $? 

clean:
	$(RM) *.o zhttp
